name: AppPackageAutoUpdate

on:
  push:
    paths:
      - 'release/AcronisCyberProtectV2.json'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Microsoft Store CLI
        uses: microsoft/microsoft-store-apppublisher@v1.1

      - name: Reconfigure store credentials
        run: msstore reconfigure `
              --tenantId ${{ secrets.AZURE_AD_TENANT_ID }} `
              --sellerId ${{ secrets.SELLER_ID }} `
              --clientId ${{ secrets.AZURE_AD_APPLICATION_CLIENT_ID }} `
              --clientSecret ${{ secrets.AZURE_AD_APPLICATION_SECRET }}
      
      - name: Update package
        run: |-
            $updatedPackage = Get-Content -Raw "${{ github.workspace }}/release/AcronisCyberProtectV2.json"
            msstore submission update <Partner center Id> $updatedPackage
      - name: Publish Submission
        run: |-
            msstore submission publish <Partner center Id>
              
